run_monitor = false
fact_collection_class = "FoundationDBFactCollection"
logging_level = "INFO"
raw_data_base_dir = "packages/fastopendata/raw_data"
data_source_config_file = "packages/fastopendata/data_sources.yml"
thread_pool_size = 10
max_queue_size = 1000
max_raw_data_queue_size = 16
max_rows_per_data_source = inf
buffer_timeout = 1.0
foundationdb_cluster_file = "/pycypher-nmetl/fdb.cluster"
prometheus_host = "prometheus"
prometheus_port = 9090
compute_mode = "thread"
sync_writes = false
grafana_host = "grafana"
grafana_port = 3000
sleep_seconds_between_retries = 1
get_item_max_attempts = 100
